apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
 # Use LoadBalancer for cloud deployments or NodePort for local setups
